### ISSUE TITLE
Señalar pie con úlcera

### ISSUE THREAD

**Issue by Adrianhernandezve** [Adrianhernandezve/ApCli_PieDiabetico#11]
- [x] Ajustar la detección 
- [x] Seleccionar pie con más temperatura
- [x] Presentar correctamente los pies

**Comment by ulewis** [comment]
- [x] Verificar que las imágenes tengan el mismo tamaño. Sino lo ajustar. 
- [x] Probar con la barra de escala de temperatura.
- [x] Mostar diferencias en temperatura [Variable que contenga la diferencia de temperatura]
